"""empty message

Revision ID: 2680a445b2ef
Revises: 
Create Date: 2019-01-28 10:06:33.023176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2680a445b2ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
